### ISSUE TITLE
App is vulnerable to api abuse

### ISSUE THREAD

**Issue by mayooear** [domeccleston/dalle-2#7]
In production, the api endpoints (especially poll and image) don't have a mechanism to prevent api abuse, which could lead to excessive AI costs and poor user experience.

Let me know if you're okay for me to create a pull request to implement api rate limiting.

**Comment by domeccleston** [comment]
Go for it! I’ll implement by tonight if not

**Comment by mayooear** [comment]
> Go for it! I’ll implement by tonight if not
> […](#)
> Sent from my iPhone
> On 17 Jan 2023, at 15:15, Mayo ***@***.***> wrote: ﻿ In production, the api endpoints (especially poll and image) don't have a mechanism to prevent api abuse, which could lead to excessive AI costs and poor user experience. Let me know if you're okay for me to create a pull request to implement api rate limiting. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

 Kl. Working on it now.

**Comment by domeccleston** [comment]
Appreciate your help Mayo, great stuff.
